version: "3"
networks: 
  hello:
    external: true

services:

  hello:
    build: .
    ports:
      - 8080
    depends_on: 
      - db
    networks:
      - hello
    environment:
      - PORT=8080
      - DIAG_PORT=8089
      - DATABASE_URL=postgres://user:pass@db/postgres?sslmode=disable

  db:
    image: postgres:10.4
    ports:
      - 5432
    environment: 
      - POSTGRES_USER=user 
      - POSTGRES_PASSWORD=pass
    networks:
      - hello
